# Generated by Django 5.2.8 on 2025-11-25 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teams", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="teampermissiondoc",
            name="is_active",
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name="teampermissiondoc",
            name="version",
            field=models.PositiveIntegerField(db_index=True),
        ),
    ]
